[package]
name = "adblock-ffi"
version = "0.1.0"
authors = ["Brian R. Bondy <netzen@gmail.com>"]
edition = "2018"

[dependencies]
adblock = { git = "https://github.com/brave/adblock-rust", rev = "cosmetic-filters" }
libc = "0.2"
rand_os = "0.1.3"
tempfile = "~3.0.8"
memoffset = "~0.5.1"

[lib]
crate-type = [
    "cdylib",
    "staticlib",
]
name = "adblock"

[features]
cbindgen = []

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"
